# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_fluent_app', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='orthophoniste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_fluent_app.Orthophoniste'),
        ),
    ]
