# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_fluent_app', '0005_auto_20160509_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedexercise',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='e_fluent_app.Exercise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignedexercise',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='e_fluent_app.Patient'),
            preserve_default=False,
        ),
    ]
