# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_fluent_app', '0006_auto_20160509_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('orthophoniste', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='e_fluent_app.Orthophoniste')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='e_fluent_app.Patient')),
            ],
        ),
    ]
