# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_fluent_app', '0007_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='orthophoniste',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='patient',
        ),
        migrations.AddField(
            model_name='orthophoniste',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_fluent_app.Meeting'),
        ),
        migrations.AddField(
            model_name='patient',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_fluent_app.Meeting'),
        ),
    ]
