# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_fluent_app', '0008_auto_20160524_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orthophoniste',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='meeting',
        ),
        migrations.AddField(
            model_name='meeting',
            name='orthophoniste',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='e_fluent_app.Orthophoniste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='e_fluent_app.Patient'),
            preserve_default=False,
        ),
    ]
