# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_fluent_app', '0010_remove_assignedexercise_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='orthophoniste',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='patient',
        ),
    ]
