# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_fluent_app', '0011_auto_20160525_0804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
