# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_fluent_app', '0013_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedexercise',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignedexercise',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='e_fluent_app.Exercise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='orthophoniste',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='e_fluent_app.Orthophoniste'),
        ),
    ]
