# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_fluent_app', '0014_auto_20160530_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedexercise',
            name='orthophoniste',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='e_fluent_app.Orthophoniste'),
            preserve_default=False,
        ),
    ]
