# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_fluent_app', '0016_remove_assignedexercise_orthophoniste'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedexercise',
            name='word',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
